import type { Metadata } from "next";
import { LightRaysBackground } from "@/components/ui/shadcn-io/light-rays-background"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground min-h-screen overflow-x-hidden relative`}>
        <LightRaysBackground 
          isBackground={true}
          fixedLightSource={true}
          raysOrigin="top-center"
          raysColor="#FFFFFF"
          raysSpeed={0.4}
          lightSpread={0.7}
          rayLength={0.5}
          fadeDistance={10}
          followMouse={false}
        />
        <LightRaysBackground 
          isBackground={true}
          fixedLightSource={true}
          raysOrigin="bottom-center"
          raysColor="#FFFFFF"
          raysSpeed={0.4}
          lightSpread={0.7}
          rayLength={0.4}
          fadeDistance={10}
          followMouse={false}
        />
        
        {/* Content layer */}
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
