import type { Metadata } from "next";
import { LightRaysBackground } from "@/components/ui/shadcn-io/light-rays-background"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white min-h-screen h-full m-0 p-0 overflow-x-hidden`}>
        {/* Background layer with light rays effect */}
        <LightRaysBackground 
          isBackground={true}
          raysOrigin="top-center"
          raysColor="#FFFFFF"
          raysSpeed={0.5}
          lightSpread={0.8}
          rayLength={2}
          fadeDistance={0.5}
          followMouse={false}
        />
        <LightRaysBackground 
          isBackground={true}
          raysOrigin="bottom-center"
          raysColor="#FFFFFF"
          raysSpeed={0.4}
          lightSpread={0.3}
          rayLength={1}
          fadeDistance={0.1}
          followMouse={false}
        />
        
        {/* Content layer */}
        <main className="relative z-10">
          {children}
        </main>
      </body>
    </html>
  );
}
